config/routes.rb
Rails.application.routes.draw do
  #index : Que devuelve una lista de recursos y es una solicitud GET del estilo /users
  #create : Que crea un nuevo recurso de los datos de solicitud 
  #show => Devuelve los contenidos de los recursos que se han identificado en params[:id] y es una  solicitud GET del estilo /users/:id
  #Update actualiza los contenidos del recurso identificado params[:id] con los datos asociados a la solicitud y es una solicitud  PUT del estilo /users/:id
  #Edit devuelve los contenidos del recurso identificado params[:id] en un formato adecuado para la edición y es una solicitud  GET del estilo /users/:id/edit
  #Destroy que destruye un recurso identificado params[:id] y es una solicitud DELETE del estilo /users/:id

#amespace :api, :path => "/", :constraints => {:subdomain => "api"} do
#namespace :api,  :path => "/", :constraints => {:subdomain => "api"}, :defaults => {:format => :json} do
	#namespace :api, :path => "/", :constraints => {:subdomain => "api"} do
	#API Definition
	namespace :api, path: '/', defaults: { format: 'json' } do
		namespace :v1 do		
			resources :projects, :only => [:show, :index]
		end
	end	

	devise_for :users
	resources :sessions, only: [:update]
    resources :projects

  #get 'projects/index'
 # get 'home/index'
 # get 'dashboard/index'
 # get 'sessions/index'
 # get 'pages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Inicio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'iCan', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <% if can? :create, Project %>
          <li><%= link_to 'Add Project', new_project_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
          <a class="dropdown-toggle" aria-expanded="false" role="button" data-toggle="dropdown" href="#">
            Role
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% User::ROLES.each do |k, v| %>
              <li>
                <%= link_to session_path(k), method: :patch do %>
                  <%= v %>
                  <% if v == current_user.role %>
                    <small class="text-muted">(current)</small>
                  <% end %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
  <%= yield %>
</div>

<div id="footer">
  <div class="container">
    <p class="text-muted">Created by <a href="#" target="_blank">Gairga</a></p>
  </div>
</div>

</body>
</html>